# Generated by Django 3.2.5 on 2021-07-24 14:26

import cloudinary.models
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kapsoya', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='neighbourhood_picture',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2021, 7, 24, 14, 26, 56, 106797, tzinfo=utc), max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
