# Generated by Django 3.2.5 on 2021-07-25 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kapsoya', '0005_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.TextField(default=datetime.datetime(2021, 7, 25, 16, 29, 1, 625109, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Crimes and Safety'), ('2', 'Health Emergency'), ('3', 'Recommendations'), ('4', 'Fire Breakouts'), ('5', 'Lost and Found'), ('6', 'Death'), ('7', 'Event')], max_length=120)),
                ('title', models.CharField(max_length=100, null=True)),
                ('post', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_post', to='kapsoya.neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='kapsoya.profile')),
            ],
        ),
    ]
