# Generated by Django 3.2.5 on 2021-07-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapsoya', '0005_neighbourhood_neighbourhood_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(null=True),
        ),
    ]
