# Generated by Django 3.2.5 on 2021-07-25 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kapsoya', '0006_alter_neighbourhood_occupants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood_description',
            field=models.TextField(default=datetime.datetime(2021, 7, 25, 8, 6, 43, 342612, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
